baseURL = 'https://links.dorrelredmond.com'
languageCode = 'en-us'
title = 'Dorrel Redmond Links'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
 name = 'Dorrel Redmond'
 # headline = "An awesome person"
 image = "img/author.png"  # path relative to static directory

# the commented links are going to be custom ones 
# will also need to redo throne as a custom, but leaving as normal link for now
 links = [
	{ link = { href = "https://dorrelredmond.com/", text = "Main Website" }},
	{ twitch = "https://twitch.tv/dorrelredmond" },
	{ twitter = "https://twitter.com/dorrelredmond" },
	{ instagram = "https://instagram.com/dorrelredmond" },
	{ discord = "https://discord.gg/UaY44UAERY" },
	{ tiktok = "https://tiktok.com/@dorrelredmond" },
	{ link = { href = "https://throne.me/u/dorrelredmond", text = "Throne" }},
	#{ ko-fi = },
	{ youtube = "https://www.youtube.com/channel/UCBMt4IJpIJ2rq3tMTMRnfOw" },
	{ apple = { href = "https://apple.co/3c0Gfao", text = "Apple Music" }},
	#{ spotify = },
	#{ amazon-music = },
	{ soundcloud = "https://soundcloud.com/dorrelredmond" },
	#{ bandcamp = },
	{ github = "https://github.com/dorrelredmond" },
	{ email = "mailto:dorrelredmond@gmail.com" },
 ]
 
