baseURL = 'http://links.dorrelredmond.com'
languageCode = 'en-us'
title = 'Dorrel Redmond Links'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
 name = 'Dorrel Redmond'
 # headline = "An awesome person"
 image = "img/author.png"  # path relative to static directory

 links = [
    { email = "mailto:dorrelredmond@gmail.com" },
    { apple = { href = "https://apple.co/3c0Gfao", text = "Apple Music" }},
    { link = "https://dorrelredmond.com/" },
    { discord = "https://discord.gg/UaY44UAERY" },
    { github = "https://github.com/dorrelredmond" },
    { instagram = "https://instagram.com/dorrelredmond" },
    { soundcloud = "https://soundcloud.com/dorrelredmond" },
    { steam = "https://steamcommunity.com/id/dorrelredmond" },
    { tiktok = "https://tiktok.com/@dorrelredmond" },
    { twitch = "https://twitch.tv/dorrelredmond" },
    { twitter = "https://twitter.com/dorrelredmond" },
    { youtube = "https://www.youtube.com/channel/UCBMt4IJpIJ2rq3tMTMRnfOw" },
 ]
 
