baseURL = 'https://links.dorrelredmond.com'
languageCode = 'en-us'
title = 'Dorrel Redmond Links'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
 name = 'Dorrel Redmond'
 # headline = "An awesome person"
 image = "author.png"  # path relative to static directory

 links = [
	{ link = { href = "https://dorrelredmond.com/", text = "Main Website" }},
	{ twitch = "https://twitch.tv/dorrelredmond" },
	{ link = {href = "https://vt.social/@dorrelredmond", text = "Mastodon"}},
	{ twitter = "https://twitter.com/dorrelredmond" },
	{ instagram = "https://instagram.com/dorrelredmond" },
	{ discord = "https://discord.gg/UaY44UAERY" },
	{ tiktok = "https://tiktok.com/@dorrelredmond" },
	{ throne = { href = "https://throne.me/u/dorrelredmond", text = "Throne" }},
	{ ko-fi = { href = "https://ko-fi.com/dorrelredmond", text = "Ko-Fi" }},
	{ link = { href = "https://www.backloggd.com/u/dorrelredmond/", text = "Game Backlog and Wishlist" }},
	{ youtube = "https://www.youtube.com/channel/UCBMt4IJpIJ2rq3tMTMRnfOw" },
	{ apple = { href = "https://apple.co/3c0Gfao", text = "Apple Music" }},
	{ spotify = { href = "https://open.spotify.com/artist/3CRJJnYhQXumwKvbQLl215", text = "Spotify" }},
	{ amazon-music = { href = "https://music.amazon.com/artists/B09R1PV2Q6/dorrel-redmond?", text = "Amazon Music"  }},
	{ soundcloud = "https://soundcloud.com/dorrelredmond" },
	{ bandcamp = { href = "https://dorrelredmond.bandcamp.com", text = "Bandcamp" }},
	{ github = "https://github.com/dorrelredmond" },
	{ email = "mailto:dorrelredmond@gmail.com" },
 ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
