baseURL = 'https://links.dorrelredmond.com'
languageCode = 'en-us'
title = 'Dorrel Redmond Links'
theme = 'lynx'

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
 name = 'Dorrel Redmond'
 # headline = "An awesome person"
 image = "author.png"  # path relative to static directory

 links = [
	{ link = { href = "https://dorrelredmond.com/", text = "Main Website" }},
	{ twitch = "https://twitch.tv/dorrelredmond" },
 	{ youtube = "https://www.youtube.com/channel/UCBMt4IJpIJ2rq3tMTMRnfOw" },
	{ twitter = "https://twitter.com/dorrelredmond" },
  	{ tiktok = "https://tiktok.com/@dorrelredmond" },
	{ discord = "https://discord.gg/UaY44UAERY" },
	{ throne = { href = "https://throne.me/u/dorrelredmond", text = "Throne" }},
	{ ko-fi = { href = "https://ko-fi.com/dorrelredmond", text = "Ko-Fi" }},
	{ apple = { href = "https://apple.co/3c0Gfao", text = "Apple Music" }},
	{ spotify = { href = "https://open.spotify.com/artist/3CRJJnYhQXumwKvbQLl215", text = "Spotify" }},
	{ soundcloud = "https://soundcloud.com/dorrelredmond" },
	{ github = "https://github.com/dorrelredmond" },
 ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
